# Generated by Django 5.2.6 on 2025-09-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='released',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
